#!/bin/bash -f
# Vivado (TM) v2016.1 (64-bit)
#
# Filename    : axi_ddr_kcu105.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu May 26 21:11:12 PDT 2016
# IP Build 1537824 on Fri Apr  8 04:28:57 MDT 2016 
#
# usage: axi_ddr_kcu105.sh [-help]
# usage: axi_ddr_kcu105.sh [-lib_map_path]
# usage: axi_ddr_kcu105.sh [-noclean_files]
# usage: axi_ddr_kcu105.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'axi_ddr_kcu105.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64 -timescale=1ps/1ps"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Script info
echo -e "axi_ddr_kcu105.sh - Script generated by export_simulation (Vivado v2016.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "/home/applications/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/applications/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
    "/home/applications/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
    "/home/applications/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
    "/home/applications/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
    "/home/applications/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
    "/home/applications/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
    "/home/applications/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/applications/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/phy/ddr4_phy_v2_0_xiphy_behav.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/phy/ddr4_phy_v2_0_xiphy.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/iob/ddr4_phy_v2_0_iob_byte.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/iob/ddr4_phy_v2_0_iob.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/clocking/ddr4_phy_v2_0_pll.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/xiphy_files/ddr4_phy_v2_0_xiphy_tristate_wrapper.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/xiphy_files/ddr4_phy_v2_0_xiphy_riuor_wrapper.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/xiphy_files/ddr4_phy_v2_0_xiphy_control_wrapper.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/xiphy_files/ddr4_phy_v2_0_xiphy_byte_wrapper.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/xiphy_files/ddr4_phy_v2_0_xiphy_bitslice_wrapper.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/phy/axi_ddr_kcu105_ddr4_0_0_phy_ddr4.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/ip_top/axi_ddr_kcu105_ddr4_0_0_phy.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_wtr.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_ref.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_rd_wr.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_periodic.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_group.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_ecc_merge_enc.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_ecc_gen.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_ecc_fi_xor.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_ecc_dec_fix.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_ecc_buf.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_ecc.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_ctl.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_cmd_mux_c.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_cmd_mux_ap.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_arb_p.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_arb_mux_p.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_arb_c.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_arb_a.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_act_timer.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc_act_rank.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/controller/ddr4_v2_0_mc.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ui/ddr4_v2_0_ui_wr_data.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ui/ddr4_v2_0_ui_rd_data.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ui/ddr4_v2_0_ui_cmd.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ui/ddr4_v2_0_ui.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_ar_channel.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_aw_channel.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_b_channel.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_cmd_arbiter.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_cmd_fsm.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_cmd_translator.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_fifo.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_incr_cmd.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_r_channel.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_w_channel.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_wr_cmd_fsm.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_wrap_cmd.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_a_upsizer.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_register_slice.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axi_upsizer.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_axic_register_slice.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_carry_and.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_carry_latch_and.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_carry_latch_or.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_carry_or.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_command_fifo.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_comparator.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_comparator_sel.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_comparator_sel_static.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_r_upsizer.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi/ddr4_v2_0_w_upsizer.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_0_axi_ctrl_addr_decode.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_0_axi_ctrl_read.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_0_axi_ctrl_reg_bank.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_0_axi_ctrl_reg.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_0_axi_ctrl_top.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_0_axi_ctrl_write.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/clocking/ddr4_v2_0_infrastructure.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_xsdb_bram.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_write.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_wr_byte.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_wr_bit.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_sync.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_riu.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_read.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_rd_en.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_pi.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_odt.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_mc_odt.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_debug_microblaze.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_cplx_data.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_cplx.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_config_rom.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_bfifo.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_addr_decode.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_top.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal_xsdb_arbiter.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_cal.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_chipscope_xsdb_slave.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal/ddr4_v2_0_dp_AB9.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top/axi_ddr_kcu105_ddr4_0_0.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top/axi_ddr_kcu105_ddr4_0_0_ddr4.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top/axi_ddr_kcu105_ddr4_0_0_ddr4_mem_intfc.sv" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/tb/microblaze_mcs_0.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_proc_sys_reset_0_0/lib_cdc_v1_0_2/hdl/src/vhdl/cdc_sync.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_9 $vhdlan_opts \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_proc_sys_reset_0_0/proc_sys_reset_v5_0_9/hdl/src/vhdl/upcnt_n.vhd" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_proc_sys_reset_0_0/proc_sys_reset_v5_0_9/hdl/src/vhdl/sequence_psr.vhd" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_proc_sys_reset_0_0/proc_sys_reset_v5_0_9/hdl/src/vhdl/lpf.vhd" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_proc_sys_reset_0_0/proc_sys_reset_v5_0_9/hdl/src/vhdl/proc_sys_reset.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_proc_sys_reset_0_0/sim/axi_ddr_kcu105_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/hdl/axi_ddr_kcu105.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_carry_and.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_carry_or.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_carry.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_mux.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/fifo_generator_v13_1_0/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_0 $vhdlan_opts \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/fifo_generator_v13_1_0/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/fifo_generator_v13_1_0/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_data_fifo_v2_1_7/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_data_fifo_v2_1_7/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_data_fifo_v2_1_7/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_data_fifo_v2_1_7/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_data_fifo_v2_1_7/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_data_fifo_v2_1_7/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_register_slice_v2_1_8/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_register_slice_v2_1_8/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_b2s.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_protocol_converter_v2_1_8/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_clock_converter_v2_1_7/hdl/verilog/axi_clock_converter_v2_1_axic_sync_clock_converter.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_clock_converter_v2_1_7/hdl/verilog/axi_clock_converter_v2_1_axic_sample_cycle_ratio.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_clock_converter_v2_1_7/hdl/verilog/axi_clock_converter_v2_1_axi_clock_converter.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/blk_mem_gen_v8_3_2/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_a_downsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_b_downsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_r_downsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_w_downsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_axi_downsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_axi4lite_downsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_axi4lite_upsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_a_upsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_r_upsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_w_upsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_w_upsizer_pktfifo.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_r_upsizer_pktfifo.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_axi_upsizer.v" \
    "$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_dwidth_converter_v2_1_8/hdl/verilog/axi_dwidth_converter_v2_1_top.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/ip_0/rtl/map" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_ddr4_0_0/rtl/ip_top" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_us_0/sim/axi_ddr_kcu105_auto_us_0.v" \
    "$ref_dir/../../../bd/axi_ddr_kcu105/ip/axi_ddr_kcu105_auto_cc_0/sim/axi_ddr_kcu105_auto_cc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.axi_ddr_kcu105 xil_defaultlib.glbl -o axi_ddr_kcu105_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./axi_ddr_kcu105_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./axi_ddr_kcu105.sh -help\" for more information)\n"
        exit 1
      fi
     create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
     create_lib_mappings $2
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Create design library directory paths and define design library mappings in cds.lib
create_lib_mappings()
{
  libs=(xil_defaultlib xpm lib_cdc_v1_0_2 proc_sys_reset_v5_0_9 generic_baseblocks_v2_1_0 fifo_generator_v13_1_0 axi_data_fifo_v2_1_7 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_8 axi_protocol_converter_v2_1_8 axi_clock_converter_v2_1_7 blk_mem_gen_v8_3_2 axi_dwidth_converter_v2_1_8)
  file="synopsys_sim.setup"
  dir="vcs"

  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  if [[ -e $dir ]]; then
    rm -rf $dir
  fi

  touch $file
  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#libs[*]}; i++ )); do
    lib="${libs[i]}"
    lib_dir="$dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
      mapping="$lib : $dir/$lib"
      echo $mapping >> $file
    fi
  done
  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi

}
# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(ucli.key axi_ddr_kcu105_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc axi_ddr_kcu105_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./axi_ddr_kcu105.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi

}

# Script usage
usage()
{
  msg="Usage: axi_ddr_kcu105.sh [-help]\n\
Usage: axi_ddr_kcu105.sh [-lib_map_path]\n\
Usage: axi_ddr_kcu105.sh [-reset_run]\n\
Usage: axi_ddr_kcu105.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
